version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:12.14.0

    
    working_directory: ~/repo

    steps:
      - checkout  #그냥 코드 가져오는 부분.

      - restore_cache:  #케쉬 전략을 사용하여 node_module에 있는걸 케쉬한다.
          keys:
            - v1-dependencies-{{ checksum "package.json" }}

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - setup_remote_docker

      - run: |
          npm test
          npm run lint
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker build -t baayoo23/cd-sample:${CIRCLE_SHA1::7} .
          docker push baayoo23/cd-sample:${CIRCLE_SHA1::7} 